spring:
    datasource:
        driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
        url: jdbc:shardingsphere:classpath:shardingsphere-config-mock.yaml
    data:
        redis:
            host: localhost
            database: 15
            port: 6379
    mvc:
        servlet:
            path: /api
    threads:
        virtual:
            enabled: true
server:
    port: 11111
