spring:
    application:
        name: system-service
    config:
        import:
            - "consul:localhost:18500"
    cloud:
        consul:
            host: localhost
            port: 18500
            discovery:
                health-check-critical-timeout: 30s
                prefer-ip-address: true
                instance-id: ${spring.application.name}:${random.uuid}
            config:
                format: yaml
