dataSources:
    master:
        dataSourceClassName: com.zaxxer.hikari.HikariDataSource
        driverClassName: org.postgresql.Driver
        jdbcUrl: jdbc:postgresql://localhost:15432/system?TimeZone=Asia/Shanghai&stringtype=unspecified
        username: admin
        password: 123456
    ds_0:
        dataSourceClassName: com.zaxxer.hikari.HikariDataSource
        driverClassName: org.postgresql.Driver
        jdbcUrl: jdbc:postgresql://localhost:25432/system?TimeZone=Asia/Shanghai&stringtype=unspecified
        username: admin
        password: 123456
    ds_1:
        dataSourceClassName: com.zaxxer.hikari.HikariDataSource
        driverClassName: org.postgresql.Driver
        jdbcUrl: jdbc:postgresql://localhost:35432/system?TimeZone=Asia/Shanghai&stringtype=unspecified
        username: admin
        password: 123456
rules:
    - !SINGLE
        tables:
            - master.public.*
        defaultDataSource: master # 默认数据源，仅在执行 CREATE TABLE 创建单表时有效。缺失值为空，表示随机单播路由。

props:
    sql-show: true
    sql-simple: false
    check-table-metadata-enabled: false
    log:
        level:
            root: debug
            org.apache.shardingsphere: trace
